# Generated by Django 2.0.6 on 2018-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_code', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_class_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('max_days_history', models.IntegerField(default=0)),
            ],
        ),
    ]
