# Generated by Django 2.0.6 on 2018-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstrategy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
