# Generated by Django 2.0.6 on 2018-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_chartstrategy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstrategy',
            name='expected_stock_direction',
            field=models.CharField(choices=[('cmpsoft', 'Computers - Software'), ('finhouse', 'Finance - Housing'), ('refinery', 'Refineries')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
