# Generated by Django 2.0.6 on 2018-08-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulator', '0008_auto_20180801_1808'),
        ('order_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.FloatField(default=0)),
                ('profit_or_loss', models.FloatField(default=0)),
                ('curr_quantity', models.IntegerField(default=0)),
                ('is_open', models.NullBooleanField(default=None)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_simulator.Symbol')),
            ],
        ),
        migrations.AddField(
            model_name='longposition',
            name='initial_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
