from django.core.management.base import BaseCommand, CommandError
from market_simulator.models     import DailySymbolData


class Command(BaseCommand):

    def handle(self, *args, **options):
        dsds = DailySymbolData.objects.filter(high_price__isnull=True)
        print ('High price == null : ', dsds.count())
        dsds = DailySymbolData.objects.filter(low_price__isnull=True)
        print ('Low price == null : ', dsds.count())
        dsds = DailySymbolData.objects.filter(start_price__isnull=True)
        print ('Start price == null : ', dsds.count())
        dsds = DailySymbolData.objects.filter(close_price__isnull=True)
        print ('Close price == null : ', dsds.count())
        should_delete_all = input('Should delete these entries: (y/n)')
        if should_delete_all == 'y':
            print ('======================\nDELETING\n======================')
            dsds = DailySymbolData.objects.filter(high_price__isnull=True)
            print ('High price == null : ', dsds.count())
            dsds.delete()
            dsds = DailySymbolData.objects.filter(low_price__isnull=True)
            print ('Low price == null : ', dsds.count())
            dsds.delete()
            dsds = DailySymbolData.objects.filter(start_price__isnull=True)
            print ('Start price == null : ', dsds.count())
            dsds.delete()
            dsds = DailySymbolData.objects.filter(close_price__isnull=True)
            print ('Close price == null : ', dsds.count())
            dsds.delete()
        dsds = DailySymbolData.objects.filter(high_price=0)
        print ('High price == 0 : ', dsds.count())
        dsds = DailySymbolData.objects.filter(low_price=0)
        print ('Low price == 0 : ', dsds.count())
        dsds = DailySymbolData.objects.filter(start_price=0)
        print ('Start price == 0 : ', dsds.count())
        dsds = DailySymbolData.objects.filter(close_price=0)
        print ('Close price == 0 : ', dsds.count())
        should_delete_all = input('Should delete these entries: (y/n)')
        if should_delete_all == 'y':
            print ('======================\nDELETING\n======================')
            dsds = DailySymbolData.objects.filter(high_price=0)
            print ('High price == 0 : ', dsds.count())
            dsds.delete()
            dsds = DailySymbolData.objects.filter(low_price=0)
            print ('Low price == 0 : ', dsds.count())
            dsds.delete()
            dsds = DailySymbolData.objects.filter(start_price=0)
            print ('Start price == 0 : ', dsds.count())
            dsds.delete()
            dsds = DailySymbolData.objects.filter(close_price=0)
            print ('Close price == 0 : ', dsds.count())
            dsds.delete()
        dsds = DailySymbolData.objects.filter(volume__isnull=True)
        print ('Volume == null : ', dsds.count())
        should_delete_all = input('Should delete these entries: (y/n)')
        if should_delete_all == 'y':
            print ('======================\nDELETING\n======================')
            dsds = DailySymbolData.objects.filter(volume__isnull=True)
            print ('Volume == null : ', dsds.count())
            dsds.delete()
        dsds = DailySymbolData.objects.filter(volume=0)
        print ('Volume == 0 : ', dsds.count())
        should_delete_all = input('Should delete these entries: (y/n)')
        if should_delete_all == 'y':
            print ('======================\nDELETING\n======================')
            dsds = DailySymbolData.objects.filter(volume=0)
            print ('Volume == 0 : ', dsds.count())
            dsds.delete()
