# Generated by Django 2.0.6 on 2018-06-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailySymbolData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('date', models.DateField()),
                ('high_time', models.DateTimeField(blank=True, null=True)),
                ('low_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_code', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_simulator.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_code', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('cmpsoft', 'Computers - Software')], max_length=100)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_simulator.Index')),
            ],
        ),
        migrations.AddField(
            model_name='dailysymboldata',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market_simulator.Symbol'),
        ),
    ]
