# Generated by Django 2.0.6 on 2018-06-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_data_source_code', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('source_class_prefix', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='index',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_simulator.Country'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_simulator.Index'),
        ),
        migrations.AddField(
            model_name='dailysymboldata',
            name='data_souce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market_simulator.MarketDataSource'),
        ),
    ]
