# Generated by Django 2.0.6 on 2018-06-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulator', '0002_auto_20180623_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysymboldata',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='close_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='high_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='low_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='start_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='index',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketdatasource',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketdatasource',
            name='market_data_source_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketdatasource',
            name='source_class_prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
