# Generated by Django 2.0.6 on 2018-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulator', '0005_auto_20180704_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysymboldata',
            name='close_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='high_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='low_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='start_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymboldata',
            name='volume',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='sector',
            field=models.CharField(choices=[('cmpsoft', 'Computers - Software'), ('finhouse', 'Finance - Housing'), ('refinery', 'Refineries'), ('pvtbank', 'Banks - Private Sector'), ('perscare', 'Personal Care'), ('cigret', 'Cigarettes'), ('autocar', 'Auto - Cars & Jeeps'), ('pubbank', 'Banks - Public Sector'), ('oil', 'Oil Drilling & Exploration'), ('infra', 'Infrastructure - General'), ('mine', 'Mining & Minerals'), ('telecom', 'Telecommunication - Services'), ('pharma', 'Pharmaceuticals'), ('leasehire', 'Finance - Leasing & Hire Purchase'), ('powergen', 'Power - Generation & Distribution'), ('metalnf', 'Metals - Non Ferrous'), ('paintvar', 'Paints & Varnishes'), ('cement', 'Cement - Major'), ('fininvest', 'Finance - Investments'), ('foodproc', 'Food Processing'), ('misc', 'Miscellaneous'), ('retail', 'Retail'), ('autolc', 'Auto - LCVS & HCVS'), ('autotwo', 'Auto - 2 Wheelers & 3 Wheelers'), ('steellar', 'Steel - Large'), ('diverse', 'Diversified'), ('autoanc', 'Auto Ancillaries'), ('fingen', 'Finance - General'), ('mediaent', 'Media & Entertainment'), ('chem', 'Chemicals'), ('telecomin', 'Telecommunications - Infrastructure'), ('alum', 'Aluminium'), ('brew', 'Breweries & Distillaries'), ('trans', 'Transport & Logistics'), ('constcont', 'Construction & Contracting - Real Estate'), ('electric', 'Electric Equipment'), ('tyres', 'Tyres'), ('textiles', 'Textiles - Readymade Apparels'), ('steeltub', 'Steel - Tubes & Pipes'), ('trading', 'Trading'), ('products', 'Products & Building Materials'), ('fertilisers', 'Fertilisers')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('symbol_code', 'index')},
        ),
    ]
