# Generated by Django 2.0.6 on 2018-08-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulator', '0007_auto_20180729_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='sector',
            field=models.CharField(choices=[('cmpsoft', 'Computers - Software'), ('finhouse', 'Finance - Housing'), ('refinery', 'Refineries'), ('pvtbank', 'Banks - Private Sector'), ('perscare', 'Personal Care'), ('cigret', 'Cigarettes'), ('autocar', 'Auto - Cars & Jeeps'), ('pubbank', 'Banks - Public Sector'), ('oil', 'Oil Drilling & Exploration'), ('infra', 'Infrastructure - General'), ('mine', 'Mining & Minerals'), ('telecom', 'Telecommunication - Services'), ('pharma', 'Pharmaceuticals'), ('leasehire', 'Finance - Leasing & Hire Purchase'), ('powergen', 'Power - Generation & Distribution'), ('metalnf', 'Metals - Non Ferrous'), ('paintvar', 'Paints & Varnishes'), ('cement', 'Cement - Major'), ('fininvest', 'Finance - Investments'), ('foodproc', 'Food Processing'), ('misc', 'Miscellaneous'), ('retail', 'Retail'), ('autolc', 'Auto - LCVS & HCVS'), ('autotwo', 'Auto - 2 Wheelers & 3 Wheelers'), ('steellar', 'Steel - Large'), ('diverse', 'Diversified'), ('autoanc', 'Auto Ancillaries'), ('fingen', 'Finance - General'), ('mediaent', 'Media & Entertainment'), ('chem', 'Chemicals'), ('telecomin', 'Telecommunications - Infrastructure'), ('alum', 'Aluminium'), ('brew', 'Breweries & Distillaries'), ('trans', 'Transport & Logistics'), ('constcont', 'Construction & Contracting - Real Estate'), ('electric', 'Electric Equipment'), ('tyres', 'Tyres'), ('textiles', 'Textiles - Readymade Apparels'), ('steeltub', 'Steel - Tubes & Pipes'), ('trading', 'Trading'), ('products', 'Products & Building Materials'), ('fertilisers', 'Fertilisers'), ('textilesco', 'Textiles - Spinning - Cotton Blended'), ('drycells', 'Dry Cells'), ('hosiery', 'Hosiery & Knitwear'), ('paper', 'Paper'), ('lubricants', 'Lubricants'), ('finterm', 'Finance - Term Lending Institutions'), ('castings', 'Castings & Forgings'), ('hotels', 'Hotels'), ('textilesman', 'Textiles - Manmade'), ('diamonds', 'Diamond Cutting & Jewellery & Precious Metals'), ('telecomequip', 'Telecommunications - Equipment'), ('electgraph', 'Electrodes & Graphite'), ('bearings', 'Bearings'), ('enggheavy', 'Engineering - Heavy'), ('steelgp', 'Steel - GP & GC Sheets'), ('dyespigments', 'Dyes & Pigments'), ('cementmini', 'Cement - Mini'), ('packaging', 'Packaging'), ('steelmed', 'Steel - Medium & Small'), ('cables', 'Cables - Power & Others'), ('textileswoolen', 'Textiles - Woolen & Worsted'), ('powertrans', 'Power - Transmission & Equipment'), ('printing', 'Printing & Stationary'), ('steelpig', 'Steel - Pig Iron'), ('sugar', 'Sugar'), ('vanspatioil', 'Vanaspati & Oils'), ('pumps', 'Pumps'), ('steelsponge', 'Steel - Sponge Iron'), ('petrochemicals', 'Petrochemicals'), ('consumergoods', 'Consumer Goods - Electronic'), ('engines', 'Engines'), ('consumergoodswhite', 'Consumer Goods - White Goods'), ('pesticides', 'Pesticides & Agro Chemicals'), ('ceramics', 'Ceramics & Granite'), ('leather', 'Leather Products'), ('detergents', 'Detergents'), ('engineering', 'Engineering'), ('cmphard', 'Computers - Hardware'), ('plantationstea', 'Plantations - Tea & Coffee'), ('hospitals', 'Hospitals & Medical Services'), ('shipping', 'Shipping'), ('plastics', 'Plastics'), ('aquaculture', 'Aquaculture'), ('couriers', 'Couriers')], max_length=100),
        ),
    ]
